version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    day: "friday"
    time: "11:00" # UTC - 13:00 Polish time
    open-pull-requests-limit: 10
    reviewers:
      - "h3x89"
    assignees:
      - "h3x89"
