# [allowlist]
# paths = [
#     '''js/datadog\.js'''
# ]

# lub bardziej precyzyjnie dla konkretnych linii
[[allowlist]]
regexes = [
    '''applicationId: ['"]ef98ba92-2942-4c3c-bccf-a0473752a05d['"]''',
    '''clientToken: ['"]pub36d6cdb75f01bb02ab01e805a1d01d0b['"]'''
]
description = "Datadog RUM public tokens"