# Konfiguracja allowlist dla gitleaks
[allowlist]
# Opcja 1: Ignorowanie całego pliku
paths = [
    '''js/datadog\.js'''
]

# Opcja 2: Ignorowanie konkretnych wzorców
[[allowlist]]
regexes = [
    '''applicationId: ['"]ef98ba92-2942-4c3c-bccf-a0473752a05d['"]''',
    '''clientToken: ['"]pub36d6cdb75f01bb02ab01e805a1d01d0b['"]'''
]
description = "Datadog RUM public tokens"